### ISSUE TITLE
Remove Microgateway Labels

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#10253]
### Description:
$subject

### Tasks:
- [x] - Remove Labels integration tests
- [x] - Remove Labels Rest APIs
- [x] - Remove Label in UIs
- [ ] - Update migration steps to DROP Labels tables
