### ISSUE TITLE
Top-Down approach to create Managed APIs (API first approach)

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/product-apim#11918]
### Describe your problem(s)
Since the APIM release of 4.0.0, we can expose an integration created in Micro Integrator/Streaming Integrator as an endpoint to API Manager so that the API developer can expose it as a managed API. However, the reverse is not possible at the moment. An API developer cannot start creating a managed API so that the integration developer can expose an integration later on.

The suggested approach for implementing this feature includes the following subtasks.

- [x] https://github.com/wso2/product-apim/issues/11917
- [x] https://github.com/wso2/integration-studio/issues/936
- [x] https://github.com/wso2/product-apim/issues/11915
- [x] https://github.com/wso2/product-apim/issues/11916
- [x] https://github.com/wso2/product-apim/issues/12170

### Affected Product Version:
APIM 4.1.0
Integration Studio 8.1.0
