### ISSUE TITLE
[Feature] Support for shared scopes and attaching multiple scopes per API resource

### ISSUE THREAD

**Issue by dushaniw** [wso2/product-apim#7292]
### Describe your problem(s)
Assume I have an application using multiple APIs and it supports functionalities for users with different types of permissions. 

For example, assume my application is using both **API A** and **B**. API A has 2 operations ( **/a GET, /a POST**) and similarly API B has 2 operations ( **/b GET, /b POST**). The users of set 1 only have read permission and set 2 have both read-write permissions. The permissions are given by assigning roles.

**set 1 user** - _role 1 (read-only role)_
**set 2 users** - _role 2 (read-write role)_

The **users of set 1** need to be provided access for **both (/a GET) and (/b GET)**. The **users of set 2** need to be provided access for **all the 4 operations (/a GET, /a POST, /b GET, /b POST)** of API A and API B. 

With the current functionality of WSO2 API-M local scopes, this can be achieved by creating 2 local scopes (view-scope, edit-scope) for each API, and define role bindings of the users based on the permissions they have. Then, assign them to the API operations.

**API A**
view-scopeA - _role1, role2_
edit-scopeA - _role2_

/a GET - view-scopeA
/a POST - edit-scopeA

**API B**
view-scopeB - _role1, role2_
edit-scopeB - _role2_

/b GET - view-scopeB
/b POST - edit-scopeB

The main limitation of the above way is that we need to create 4 scopes separately with 4 unique scope keys duplicating the scope-role bindings. This will be a tedious and time-consuming task when the number of APIs and scopes are large.

### Describe your solution
To overcome the duplicating effort of creating the same scope (using the same role bindings) with unique keys for multiple APIs, it is ideal to have the capability to define the scope-role bindings globally and reuse them in the API operations. So the API developers can restrict access for the API operations of the APIs globally.  

- Global OAuth2 Scopes are useful when an organization/department (a tenant) has a need to globally control the fined grained access control permissions of all the published APIs, from a central place.  

- It reduces the rework of creating the same scope with duplicate access control permissions for each of the API. With this, such scope creation would be a one time task. Global scopes will be created by administrative users and the API developers can attach the available global scopes for the API resources when designing the API.

So there will be only two scopes that need to be created globally.
view-scope - _role1, role2_
edit-scope - _role2_

**API A**
/a GET - _view-scope_
/a POST - _edit-scope_

**API B**
/b GET - _view-scope_
/b POST - _edit-scope_

In addition to the above, if there will be later requirement where there is another set of users with a different set of permissions (role3) and they need to be given permission to use (/b GET) operation of API B. If so, with the above design where we do not support multiple scopes per resource, we need to create another new scope with all role1, role2, and role3 bindings. Then assign it for (/b GET) instead of edit-scope. In that case, the point of reusing global scopes across multiple APIs would not become beneficial. Hence, by supporting multiple scopes per resource, we can keep the above design as it is and separately create a global/local scope with bindings for role3 and attach it to (/b GET) operation.

new-scope - role3

**API B**
/b GET _view-scope, new-scope_
/b POST _edit-scope_

### How will you implement it

- **The global scope management view will be added to the Publisher UI** so that the API developers can easily check what are the available global scopes and their role bindings from the same portal when creating an API. 

- Current Publisher Portal UI for Resource Management of an API will be modified to attach the global scopes and attach multiple scopes per resource.
- To make sure that only privileged users(admins) can add/update/delete any global scope, the relevant Publisher REST APIs and UI will be secured using a REST API scope. Eg: apim:global_scope_manage
- To support global scopes, we need to add a new table AM_GLOBAL_SCOPE on AM_DB.

```
AM_GLOBAL_SCOPE
     SCOPE_ID INTEGER NOT NULL,
     TENANT_ID INTEGER DEFAULT -1,
     UUID VARCHAR (256)
```

- Need to modify the PK constraint on IDN_OAUTH2_RESOURCE_SCOPE to be a composite key on both RESOURCE_PATH and SCOPE_ID to support multiple scopes per resource.

```
IDN_OAUTH2_RESOURCE_SCOPE 
       RESOURCE_PATH VARCHAR(255) NOT NULL,
       SCOPE_ID INTEGER NOT NULL,
       TENANT_ID INTEGER DEFAULT -1,
       PRIMARY KEY (SCOPE_ID, RESOURCE_PATH),
       FOREIGN KEY (SCOPE_ID) REFERENCES IDN_OAUTH2_SCOPE (SCOPE_ID) ON DELETE CASCADE
```

- JDBCScopeValidator will be modified to support validating multiple scopes attached per resource [1]

- Global Scopes will be added via the following Publisher REST APIs. Using the resource name "global-scopes" seems more appropriate since these REST APIs will be used to only manage global scopes. The "Scope" resource and "ScopeList" resource are already defined in Publisher REST API, hence we can use the same resources for global-scopes as well. 
   /global-scopes : GET, POST
   /global-scopes/{scopeId} : GET, PUT, DELETE

#### Flow
1. A privileged user/administrative user logs into Publisher Portal and creates a global scope providing name, description and role bindings. 
2. Upon checking whether the scope key is not duplicated in the IDN_OAUTH2_SCOPE table, this scope will be added to the IDN_OAUTH2_SCOPE, IDN_OAUTH2_SCOPE2_BINDING and AM_GLOBAL_SCOPE tables. 
3. An API developer creates an API and visits the resources page. The list of scopes to add per resource is populated using the per-API scope from the API object and from the "GET /global-scopes" backend service call.
4. The developer selects a set of global/per-API scope for the resource. The swagger is updated with the scopes list and resource scope list. The backend service "PUT apis/{apiId}/swagger" updates the IDN_OAUTH2_RESOURCE_SCOPE and AM_API_SCOPES table.
5. App Developer will generate a token with the scopes and invoke the API. During the KeyValidation service, when the scopes are validated for the resource using the JDBCScopeValidator, it will check whether token bears any of the given resource scopes.

---

[1] https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/master/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth2/validators/JDBCScopeValidator.java#L78

**Comment by dushaniw** [comment]
The DB diagram would like this,

Please note the IDN_OAUTH2_RESOURCE_SCOPE table is being modified for testing purposes since we have not yet implemented the scope issuing and scope validation part with KM separation architecture.

![after_db_diagram](https://user-images.githubusercontent.com/12208083/79428469-d1a86800-7fe3-11ea-8ab7-cd74e70efb97.png)

**Comment by dushaniw** [comment]
The feature's name Global Scopes is changed to Shared Scopes, as the intention of this is for the APIs in the same tenant domain to share the scopes among them.

**Comment by dushaniw** [comment]
- The /global-scopes resource is renamed to /scopes since those shared scopes are anyway in the global/root level (not under an API). 

- Removed the binding type of ScopeDTO resource as we are only allowing role type bindings from Publisher. So now the ScopeDTO resource will have an array object named bindings consisting of the roles of the scope.

- ATM, **we are still supporting local (per-API) scopes** that uses the same ScopeDTO resource. We need to differentiate the shared scopes from the per-API scopes from the APIDTO.scopes array, to restrict changing shared scopes from per-API scope UI. Hence, added another parameter, "isShared" when adding ScopeDTOs to APIDTO.scopes array. 

- The shared scope Add, Update, Deletion will be allowed for users with, `apim:shared_scope_manage` REST API scope.

The changes reflecting the above in Publisher REST API is attached here. 
[publisher-api-shared-scopes.zip](https://github.com/wso2/product-apim/files/4527688/publisher-api-shared-scopes.zip)

**TODO:**
- [ ] Prior to above change, we already had defined "/scopes/{scopeName}" resource with a HEAD operation to check a particular scope name is already defined for the current tenant. However, with the introduction of the above changes, we are violating the APIDefinition schema rule by having equivalent paths in two places (`/scopes/{scopeId} `and `/scopes/{scopeName}`). We need to fix this issue, either by changing `/scopes/{scopeName} HEAD` to `/scopes?scopeName={scopeName}` HEAD`.

**Comment by dushaniw** [comment]
The updated DB Diagram.

![current](https://user-images.githubusercontent.com/12208083/80197767-bd481900-863c-11ea-87fb-694d6a3eca24.png)

**Comment by dushaniw** [comment]
- Multiple scopes per resource are supported from the DB level and OASParser level with [this](https://github.com/wso2/carbon-apimgt/pull/8409/commits/45e4209e29a934ee0cd45c6ecd7c83669a55c017).

- when `preserveLegacyExtension` system property is enabled (`x-wso2-scope` is preserved for each operation), multiple scopes per operation should be given under `x-wso2-scope : OrderScope,MenuScope`. Scopes should be given as a string separated with comma(,).

**TODOs:** 

- [ ] Fix the OAS Parsing accordingly in Gateway for BasicAuthentication and JWTAuthentication.
- [ ] Both scope key and name are given in Scope model object. Need to fix places where scope key is set and access, by moving them to set and access scope name.

**Comment by dushaniw** [comment]
### Support Attaching/Detaching Shared Scopes to/from APIs

**Comment by dushaniw** [comment]
The following are the proposed UIs.

### Scopes View 
![Scopes View UI](https://user-images.githubusercontent.com/12208083/80320377-b800ef00-8833-11ea-9c39-ac53596a82d4.png)

### Create Scope
![createScope](https://user-images.githubusercontent.com/12208083/80320428-eed70500-8833-11ea-8ddf-1b7dba2f853a.png)

### Update Scope
![updateScope](https://user-images.githubusercontent.com/12208083/80320430-f0a0c880-8833-11ea-99df-103b62df0f89.png)

### Scope Usage in APIs [Read Only]
![scopeAPIUsages](https://user-images.githubusercontent.com/12208083/80320435-f696a980-8833-11ea-97a1-626af830f795.png)

### Scope Usage in {API}-{Version}
![ScopeAPIResourceUsages](https://user-images.githubusercontent.com/12208083/80320439-fe564e00-8833-11ea-9df9-81fb0bbbc313.png)
