### ISSUE TITLE
Service catalog feature for APIM 4

### ISSUE THREAD

**Issue by tmkasun** [wso2/product-apim#9420]
The main objective of the Service Catalog would be to create a connection between API Management and Integration layers by making integration services discoverable to the API Management layer.

- [x] [Reposition the Global Nav Bar elements with a drawer in Publisher](https://github.com/wso2/product-apim/issues/9437)
- [x] [Implement an API Client for Service Catalog UI](https://github.com/wso2/product-apim/issues/9471)
- [x] [Implement Service Catalog Onboarding](https://github.com/wso2/product-apim/issues/9470) 
- [x] [Implement Service Catalog Listing View](https://github.com/wso2/product-apim/issues/9510)
- [x] [Create an Overview page for the Service Catalog Feature](https://github.com/wso2/product-apim/issues/9622)
- [x] [Add option to Create an API using a service in Service Catalog](https://github.com/wso2/product-apim/issues/9625)
- [x] [Allow updating an API when its service is updated in Service Catalog](https://github.com/wso2/product-apim/issues/9626)
- [x] [Revamp Service Catalog UI with review suggestions](https://github.com/wso2/carbon-apimgt/pull/9561)

**Comment by malinthaprasan** [comment]
Feature was completed.
