### ISSUE TITLE
Virtual Hosts - (VHosts)

### ISSUE THREAD

**Issue by renuka-fernando** [wso2/product-apim#9807]
### Describe your problem(s)
Virtual Hosts enables users to expose APIs using different host names while serving gateway on a single server (or pool of servers).

Admin users should be able to manage VHosts by creating, updating and deleting VHosts and assign a VHost to gateway environment(s). API publishers should be able to deploy an API to the gateway environment(s), assign a VHost per gateway environment.

#### Subtasks
- [x] - Manage VHosts in Admin Portal
- [x] - Assign VHosts and deploy with API revisions in Publisher Portal
- [x] - Tryout in DevPortal
- [x] - Label Migration
- [x] - Remove Microgateway Labels - https://github.com/wso2/product-apim/issues/10253
- [x] - Remove Private Jet Feature - https://github.com/wso2/product-apim/issues/10378
- [x] - Create deployment descritpro for Microgateway

**Comment by malinthaprasan** [comment]
@renuka-fernando please close the issue once the implementation is completed.
